// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/color-compare/AmberCopper.tsx": () => import("../components/mockups/color-compare/AmberCopper.tsx"),
  "./components/mockups/color-compare/DustyViolet.tsx": () => import("../components/mockups/color-compare/DustyViolet.tsx")
};
